// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbsPath(arg1) {
	return window['go']['api']['App']['AbsPath'](arg1)
}

export function CreateStudy(arg1, arg2) {
	return window['go']['api']['App']['CreateStudy'](arg1, arg2)
}

export function LoadStudy(arg1) {
	return window['go']['api']['App']['LoadStudy'](arg1)
}

export function ParentPath(arg1) {
	return window['go']['api']['App']['ParentPath'](arg1)
}

export function ReadDir(arg1) {
	return window['go']['api']['App']['ReadDir'](arg1)
}
