// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { study } from '../models'
import { api } from '../models'

export function AbsPath(arg1: string): Promise<string>

export function LoadStudy(arg1: string): Promise<study.Study>

export function ParentPath(arg1: string): Promise<string>

export function ReadDir(arg1: string): Promise<Array<api.DirInfo>>
