#!/bin/bash

clear
set -e
tabs -2

printUsage() {
	println "Usage:"
	println "\t" "./godo [help]" "\t\t" "Print usage"
	println "\t" "./godo clean " "\t\t" "Clean Go caches"
	println "\t" "./godo tidy  " "\t\t" "Tidy go.mod"
	println "\t" "./godo fmt   " "\t\t" "format"
	println "\t" "./godo test  " "\t\t" "fmt -> build -> test -> vet"
	println "\t" "./godo commit" "\t\t" "clean -> tidy -> fmt -> build -> test -> vet"
}

println() {
	for s in "$@"
	do
		printf "$s"
	done
	printf "\\n"
}

# TODO
